/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FornecedorRouteImport } from './routes/fornecedor'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FornecedorIndexRouteImport } from './routes/fornecedor.index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedControladoriaRouteImport } from './routes/_authenticated.controladoria'
import { Route as AuthenticatedControladoriaPrestadoresRouteImport } from './routes/_authenticated.controladoria.prestadores'
import { Route as AuthenticatedControladoriaAprovacoesRouteImport } from './routes/_authenticated.controladoria.aprovacoes'
import { Route as AuthenticatedControladoriaPrestadoresNovoRouteImport } from './routes/_authenticated.controladoria.prestadores.novo'
import { Route as AuthenticatedControladoriaPrestadoresIdRouteImport } from './routes/_authenticated.controladoria.prestadores.$id'
import { Route as AuthenticatedControladoriaContratosIdRouteImport } from './routes/_authenticated.controladoria.contratos.$id'
import { Route as AuthenticatedControladoriaSolicitacoesIdFichaRouteImport } from './routes/_authenticated.controladoria.solicitacoes.$id.ficha'

const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorRoute = FornecedorRouteImport.update({
  id: '/fornecedor',
  path: '/fornecedor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorIndexRoute = FornecedorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FornecedorRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedControladoriaRoute =
  AuthenticatedControladoriaRouteImport.update({
    id: '/controladoria',
    path: '/controladoria',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedControladoriaPrestadoresRoute =
  AuthenticatedControladoriaPrestadoresRouteImport.update({
    id: '/prestadores',
    path: '/prestadores',
    getParentRoute: () => AuthenticatedControladoriaRoute,
  } as any)
const AuthenticatedControladoriaAprovacoesRoute =
  AuthenticatedControladoriaAprovacoesRouteImport.update({
    id: '/aprovacoes',
    path: '/aprovacoes',
    getParentRoute: () => AuthenticatedControladoriaRoute,
  } as any)
const AuthenticatedControladoriaPrestadoresNovoRoute =
  AuthenticatedControladoriaPrestadoresNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedControladoriaPrestadoresRoute,
  } as any)
const AuthenticatedControladoriaPrestadoresIdRoute =
  AuthenticatedControladoriaPrestadoresIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedControladoriaPrestadoresRoute,
  } as any)
const AuthenticatedControladoriaContratosIdRoute =
  AuthenticatedControladoriaContratosIdRouteImport.update({
    id: '/contratos/$id',
    path: '/contratos/$id',
    getParentRoute: () => AuthenticatedControladoriaRoute,
  } as any)
const AuthenticatedControladoriaSolicitacoesIdFichaRoute =
  AuthenticatedControladoriaSolicitacoesIdFichaRouteImport.update({
    id: '/solicitacoes/$id/ficha',
    path: '/solicitacoes/$id/ficha',
    getParentRoute: () => AuthenticatedControladoriaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fornecedor': typeof FornecedorRouteWithChildren
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/controladoria': typeof AuthenticatedControladoriaRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fornecedor/': typeof FornecedorIndexRoute
  '/controladoria/aprovacoes': typeof AuthenticatedControladoriaAprovacoesRoute
  '/controladoria/prestadores': typeof AuthenticatedControladoriaPrestadoresRouteWithChildren
  '/controladoria/contratos/$id': typeof AuthenticatedControladoriaContratosIdRoute
  '/controladoria/prestadores/$id': typeof AuthenticatedControladoriaPrestadoresIdRoute
  '/controladoria/prestadores/novo': typeof AuthenticatedControladoriaPrestadoresNovoRoute
  '/controladoria/solicitacoes/$id/ficha': typeof AuthenticatedControladoriaSolicitacoesIdFichaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/controladoria': typeof AuthenticatedControladoriaRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fornecedor': typeof FornecedorIndexRoute
  '/controladoria/aprovacoes': typeof AuthenticatedControladoriaAprovacoesRoute
  '/controladoria/prestadores': typeof AuthenticatedControladoriaPrestadoresRouteWithChildren
  '/controladoria/contratos/$id': typeof AuthenticatedControladoriaContratosIdRoute
  '/controladoria/prestadores/$id': typeof AuthenticatedControladoriaPrestadoresIdRoute
  '/controladoria/prestadores/novo': typeof AuthenticatedControladoriaPrestadoresNovoRoute
  '/controladoria/solicitacoes/$id/ficha': typeof AuthenticatedControladoriaSolicitacoesIdFichaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/fornecedor': typeof FornecedorRouteWithChildren
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_authenticated/controladoria': typeof AuthenticatedControladoriaRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/fornecedor/': typeof FornecedorIndexRoute
  '/_authenticated/controladoria/aprovacoes': typeof AuthenticatedControladoriaAprovacoesRoute
  '/_authenticated/controladoria/prestadores': typeof AuthenticatedControladoriaPrestadoresRouteWithChildren
  '/_authenticated/controladoria/contratos/$id': typeof AuthenticatedControladoriaContratosIdRoute
  '/_authenticated/controladoria/prestadores/$id': typeof AuthenticatedControladoriaPrestadoresIdRoute
  '/_authenticated/controladoria/prestadores/novo': typeof AuthenticatedControladoriaPrestadoresNovoRoute
  '/_authenticated/controladoria/solicitacoes/$id/ficha': typeof AuthenticatedControladoriaSolicitacoesIdFichaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fornecedor'
    | '/login'
    | '/nova-senha'
    | '/recuperar-senha'
    | '/controladoria'
    | '/dashboard'
    | '/fornecedor/'
    | '/controladoria/aprovacoes'
    | '/controladoria/prestadores'
    | '/controladoria/contratos/$id'
    | '/controladoria/prestadores/$id'
    | '/controladoria/prestadores/novo'
    | '/controladoria/solicitacoes/$id/ficha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/nova-senha'
    | '/recuperar-senha'
    | '/controladoria'
    | '/dashboard'
    | '/fornecedor'
    | '/controladoria/aprovacoes'
    | '/controladoria/prestadores'
    | '/controladoria/contratos/$id'
    | '/controladoria/prestadores/$id'
    | '/controladoria/prestadores/novo'
    | '/controladoria/solicitacoes/$id/ficha'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/fornecedor'
    | '/login'
    | '/nova-senha'
    | '/recuperar-senha'
    | '/_authenticated/controladoria'
    | '/_authenticated/dashboard'
    | '/fornecedor/'
    | '/_authenticated/controladoria/aprovacoes'
    | '/_authenticated/controladoria/prestadores'
    | '/_authenticated/controladoria/contratos/$id'
    | '/_authenticated/controladoria/prestadores/$id'
    | '/_authenticated/controladoria/prestadores/novo'
    | '/_authenticated/controladoria/solicitacoes/$id/ficha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FornecedorRoute: typeof FornecedorRouteWithChildren
  LoginRoute: typeof LoginRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor': {
      id: '/fornecedor'
      path: '/fornecedor'
      fullPath: '/fornecedor'
      preLoaderRoute: typeof FornecedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/': {
      id: '/fornecedor/'
      path: '/'
      fullPath: '/fornecedor/'
      preLoaderRoute: typeof FornecedorIndexRouteImport
      parentRoute: typeof FornecedorRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/controladoria': {
      id: '/_authenticated/controladoria'
      path: '/controladoria'
      fullPath: '/controladoria'
      preLoaderRoute: typeof AuthenticatedControladoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/controladoria/prestadores': {
      id: '/_authenticated/controladoria/prestadores'
      path: '/prestadores'
      fullPath: '/controladoria/prestadores'
      preLoaderRoute: typeof AuthenticatedControladoriaPrestadoresRouteImport
      parentRoute: typeof AuthenticatedControladoriaRoute
    }
    '/_authenticated/controladoria/aprovacoes': {
      id: '/_authenticated/controladoria/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/controladoria/aprovacoes'
      preLoaderRoute: typeof AuthenticatedControladoriaAprovacoesRouteImport
      parentRoute: typeof AuthenticatedControladoriaRoute
    }
    '/_authenticated/controladoria/prestadores/novo': {
      id: '/_authenticated/controladoria/prestadores/novo'
      path: '/novo'
      fullPath: '/controladoria/prestadores/novo'
      preLoaderRoute: typeof AuthenticatedControladoriaPrestadoresNovoRouteImport
      parentRoute: typeof AuthenticatedControladoriaPrestadoresRoute
    }
    '/_authenticated/controladoria/prestadores/$id': {
      id: '/_authenticated/controladoria/prestadores/$id'
      path: '/$id'
      fullPath: '/controladoria/prestadores/$id'
      preLoaderRoute: typeof AuthenticatedControladoriaPrestadoresIdRouteImport
      parentRoute: typeof AuthenticatedControladoriaPrestadoresRoute
    }
    '/_authenticated/controladoria/contratos/$id': {
      id: '/_authenticated/controladoria/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/controladoria/contratos/$id'
      preLoaderRoute: typeof AuthenticatedControladoriaContratosIdRouteImport
      parentRoute: typeof AuthenticatedControladoriaRoute
    }
    '/_authenticated/controladoria/solicitacoes/$id/ficha': {
      id: '/_authenticated/controladoria/solicitacoes/$id/ficha'
      path: '/solicitacoes/$id/ficha'
      fullPath: '/controladoria/solicitacoes/$id/ficha'
      preLoaderRoute: typeof AuthenticatedControladoriaSolicitacoesIdFichaRouteImport
      parentRoute: typeof AuthenticatedControladoriaRoute
    }
  }
}

interface AuthenticatedControladoriaPrestadoresRouteChildren {
  AuthenticatedControladoriaPrestadoresIdRoute: typeof AuthenticatedControladoriaPrestadoresIdRoute
  AuthenticatedControladoriaPrestadoresNovoRoute: typeof AuthenticatedControladoriaPrestadoresNovoRoute
}

const AuthenticatedControladoriaPrestadoresRouteChildren: AuthenticatedControladoriaPrestadoresRouteChildren =
  {
    AuthenticatedControladoriaPrestadoresIdRoute:
      AuthenticatedControladoriaPrestadoresIdRoute,
    AuthenticatedControladoriaPrestadoresNovoRoute:
      AuthenticatedControladoriaPrestadoresNovoRoute,
  }

const AuthenticatedControladoriaPrestadoresRouteWithChildren =
  AuthenticatedControladoriaPrestadoresRoute._addFileChildren(
    AuthenticatedControladoriaPrestadoresRouteChildren,
  )

interface AuthenticatedControladoriaRouteChildren {
  AuthenticatedControladoriaAprovacoesRoute: typeof AuthenticatedControladoriaAprovacoesRoute
  AuthenticatedControladoriaPrestadoresRoute: typeof AuthenticatedControladoriaPrestadoresRouteWithChildren
  AuthenticatedControladoriaContratosIdRoute: typeof AuthenticatedControladoriaContratosIdRoute
  AuthenticatedControladoriaSolicitacoesIdFichaRoute: typeof AuthenticatedControladoriaSolicitacoesIdFichaRoute
}

const AuthenticatedControladoriaRouteChildren: AuthenticatedControladoriaRouteChildren =
  {
    AuthenticatedControladoriaAprovacoesRoute:
      AuthenticatedControladoriaAprovacoesRoute,
    AuthenticatedControladoriaPrestadoresRoute:
      AuthenticatedControladoriaPrestadoresRouteWithChildren,
    AuthenticatedControladoriaContratosIdRoute:
      AuthenticatedControladoriaContratosIdRoute,
    AuthenticatedControladoriaSolicitacoesIdFichaRoute:
      AuthenticatedControladoriaSolicitacoesIdFichaRoute,
  }

const AuthenticatedControladoriaRouteWithChildren =
  AuthenticatedControladoriaRoute._addFileChildren(
    AuthenticatedControladoriaRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedControladoriaRoute: typeof AuthenticatedControladoriaRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedControladoriaRoute: AuthenticatedControladoriaRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface FornecedorRouteChildren {
  FornecedorIndexRoute: typeof FornecedorIndexRoute
}

const FornecedorRouteChildren: FornecedorRouteChildren = {
  FornecedorIndexRoute: FornecedorIndexRoute,
}

const FornecedorRouteWithChildren = FornecedorRoute._addFileChildren(
  FornecedorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FornecedorRoute: FornecedorRouteWithChildren,
  LoginRoute: LoginRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
