/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedControladoriaRouteImport } from './routes/_authenticated.controladoria'
import { Route as AuthenticatedControladoriaPrestadoresRouteImport } from './routes/_authenticated.controladoria.prestadores'
import { Route as AuthenticatedControladoriaPrestadoresNovoRouteImport } from './routes/_authenticated.controladoria.prestadores.novo'

const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedControladoriaRoute =
  AuthenticatedControladoriaRouteImport.update({
    id: '/controladoria',
    path: '/controladoria',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedControladoriaPrestadoresRoute =
  AuthenticatedControladoriaPrestadoresRouteImport.update({
    id: '/prestadores',
    path: '/prestadores',
    getParentRoute: () => AuthenticatedControladoriaRoute,
  } as any)
const AuthenticatedControladoriaPrestadoresNovoRoute =
  AuthenticatedControladoriaPrestadoresNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedControladoriaPrestadoresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/controladoria': typeof AuthenticatedControladoriaRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/controladoria/prestadores': typeof AuthenticatedControladoriaPrestadoresRouteWithChildren
  '/controladoria/prestadores/novo': typeof AuthenticatedControladoriaPrestadoresNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/controladoria': typeof AuthenticatedControladoriaRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/controladoria/prestadores': typeof AuthenticatedControladoriaPrestadoresRouteWithChildren
  '/controladoria/prestadores/novo': typeof AuthenticatedControladoriaPrestadoresNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_authenticated/controladoria': typeof AuthenticatedControladoriaRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/controladoria/prestadores': typeof AuthenticatedControladoriaPrestadoresRouteWithChildren
  '/_authenticated/controladoria/prestadores/novo': typeof AuthenticatedControladoriaPrestadoresNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/nova-senha'
    | '/recuperar-senha'
    | '/controladoria'
    | '/dashboard'
    | '/controladoria/prestadores'
    | '/controladoria/prestadores/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/nova-senha'
    | '/recuperar-senha'
    | '/controladoria'
    | '/dashboard'
    | '/controladoria/prestadores'
    | '/controladoria/prestadores/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/nova-senha'
    | '/recuperar-senha'
    | '/_authenticated/controladoria'
    | '/_authenticated/dashboard'
    | '/_authenticated/controladoria/prestadores'
    | '/_authenticated/controladoria/prestadores/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/controladoria': {
      id: '/_authenticated/controladoria'
      path: '/controladoria'
      fullPath: '/controladoria'
      preLoaderRoute: typeof AuthenticatedControladoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/controladoria/prestadores': {
      id: '/_authenticated/controladoria/prestadores'
      path: '/prestadores'
      fullPath: '/controladoria/prestadores'
      preLoaderRoute: typeof AuthenticatedControladoriaPrestadoresRouteImport
      parentRoute: typeof AuthenticatedControladoriaRoute
    }
    '/_authenticated/controladoria/prestadores/novo': {
      id: '/_authenticated/controladoria/prestadores/novo'
      path: '/novo'
      fullPath: '/controladoria/prestadores/novo'
      preLoaderRoute: typeof AuthenticatedControladoriaPrestadoresNovoRouteImport
      parentRoute: typeof AuthenticatedControladoriaPrestadoresRoute
    }
  }
}

interface AuthenticatedControladoriaPrestadoresRouteChildren {
  AuthenticatedControladoriaPrestadoresNovoRoute: typeof AuthenticatedControladoriaPrestadoresNovoRoute
}

const AuthenticatedControladoriaPrestadoresRouteChildren: AuthenticatedControladoriaPrestadoresRouteChildren =
  {
    AuthenticatedControladoriaPrestadoresNovoRoute:
      AuthenticatedControladoriaPrestadoresNovoRoute,
  }

const AuthenticatedControladoriaPrestadoresRouteWithChildren =
  AuthenticatedControladoriaPrestadoresRoute._addFileChildren(
    AuthenticatedControladoriaPrestadoresRouteChildren,
  )

interface AuthenticatedControladoriaRouteChildren {
  AuthenticatedControladoriaPrestadoresRoute: typeof AuthenticatedControladoriaPrestadoresRouteWithChildren
}

const AuthenticatedControladoriaRouteChildren: AuthenticatedControladoriaRouteChildren =
  {
    AuthenticatedControladoriaPrestadoresRoute:
      AuthenticatedControladoriaPrestadoresRouteWithChildren,
  }

const AuthenticatedControladoriaRouteWithChildren =
  AuthenticatedControladoriaRoute._addFileChildren(
    AuthenticatedControladoriaRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedControladoriaRoute: typeof AuthenticatedControladoriaRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedControladoriaRoute: AuthenticatedControladoriaRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
